const fs = require('fs');
const q = require('./questions');

q["Islamic Religious Studies"] = [
  {question:"Islam means:",options:["Submission to the will of Allah","Wealth","Power","Trade"],answer:0},
  {question:"A person who submits to Allah is called a:",options:["Muslim","Christian","Priest","Monk"],answer:0},
  {question:"The holy book of Islam is the:",options:["Qur'an","Bible","Torah only","Psalms"],answer:0},
  {question:"The first revelation of the Qur'an came to:",options:["Prophet Muhammad","Prophet Musa","Prophet Isa","Prophet Ibrahim"],answer:0},
  {question:"The first revelation came through the angel:",options:["Jibril","Mikail","Israfil","Malik"],answer:0},
  {question:"The first revelation occurred in the cave of:",options:["Hira","Thawr","Uhud","Safaa"],answer:0},
  {question:"The Prophet Muhammad was born in:",options:["Makkah","Madinah","Cairo","Baghdad"],answer:0},
  {question:"The Prophet Muhammad migrated from Makkah to:",options:["Madinah","Cairo","Jerusalem","Damascus"],answer:0},
  {question:"The migration of the Prophet to Madinah is called:",options:["Hijrah","Hajj","Zakat","Jihad"],answer:0},
  {question:"The Islamic calendar begins from the:",options:["Hijrah","Birth of Muhammad","Conquest of Makkah","Battle of Badr"],answer:0},
  {question:"The first pillar of Islam is:",options:["Shahadah","Zakat","Sawm","Hajj"],answer:0},
  {question:"Salah refers to:",options:["Prayer","Fasting","Charity","Pilgrimage"],answer:0},
  {question:"Muslims perform obligatory prayers how many times daily?",options:["Five","Three","Seven","Ten"],answer:0},
  {question:"Zakat is:",options:["Obligatory charity","Pilgrimage","Fasting","Prayer"],answer:0},
  {question:"Sawm means:",options:["Fasting","Prayer","Charity","Pilgrimage"],answer:0},
  {question:"Hajj means:",options:["Pilgrimage to Makkah","Daily prayer","Fasting","Charity"],answer:0},
  {question:"Hajj is performed in the Islamic month of:",options:["Dhul-Hijjah","Ramadan","Muharram","Rajab"],answer:0},
  {question:"Fasting during Ramadan is called:",options:["Sawm","Salah","Zakat","Hajj"],answer:0},
  {question:"The month of fasting is:",options:["Ramadan","Shawwal","Muharram","Safar"],answer:0},
  {question:"The festival marking the end of Ramadan is:",options:["Eid al-Fitr","Eid al-Adha","Mawlid","Ashura"],answer:0},
  {question:"Eid al-Adha is associated with:",options:["Hajj and sacrifice","Beginning of Ramadan","Daily prayer","Hijrah"],answer:0},
  {question:"The direction Muslims face during prayer is the:",options:["Qiblah","Minbar","Mihrab","Ka'bah"],answer:0},
  {question:"The Ka'bah is located in:",options:["Makkah","Madinah","Cairo","Jerusalem"],answer:0},
  {question:"The first mosque built by the Prophet after migration was:",options:["Quba Mosque","Al-Aqsa Mosque","Great Mosque of Makkah","Blue Mosque"],answer:0},
  {question:"The Prophet Muhammad died in:",options:["Madinah","Makkah","Cairo","Damascus"],answer:0},
  {question:"The first caliph after Prophet Muhammad was:",options:["Abu Bakr","Umar","Uthman","Ali"],answer:0},
  {question:"The second rightly guided caliph was:",options:["Umar ibn al-Khattab","Abu Bakr","Uthman","Ali"],answer:0},
  {question:"The third rightly guided caliph was:",options:["Uthman ibn Affan","Umar","Ali","Abu Bakr"],answer:0},
  {question:"The fourth rightly guided caliph was:",options:["Ali ibn Abi Talib","Uthman","Umar","Abu Bakr"],answer:0},
  {question:"The Qur'an was revealed in:",options:["Arabic","Hebrew","Latin","Greek"],answer:0},
  {question:"The Qur'an is divided into chapters called:",options:["Surahs","Ayahs only","Hadiths","Fiqhs"],answer:0},
  {question:"A verse of the Qur'an is called an:",options:["Ayah","Sunnah","Imam","Hadith"],answer:0},
  {question:"Hadith refers to reports about the Prophet's:",options:["Words, actions and approvals","Wealth only","Family tree only","Battles only"],answer:0},
  {question:"Sunnah refers to the:",options:["Way and example of the Prophet","Qur'an only","Islamic calendar","Mosque"],answer:0},
  {question:"Tawhid means:",options:["Oneness of Allah","Pilgrimage","Charity","Fasting"],answer:0},
  {question:"Shirk means:",options:["Associating partners with Allah","Giving charity","Prayer","Fasting"],answer:0},
  {question:"The angel responsible for delivering revelation is:",options:["Jibril","Mikail","Israfil","Malik"],answer:0},
  {question:"The angel associated with blowing the trumpet is:",options:["Israfil","Jibril","Mikail","Malik"],answer:0},
  {question:"The angel associated with taking souls is:",options:["Malak al-Mawt","Jibril","Mikail","Israfil"],answer:0},
  {question:"Makkah was conquered by the Muslims in:",options:["630 CE","610 CE","622 CE","632 CE"],answer:0},
  {question:"The Battle of Badr took place in:",options:["624 CE","625 CE","627 CE","630 CE"],answer:0},
  {question:"The Battle of Uhud took place in:",options:["625 CE","624 CE","627 CE","630 CE"],answer:0},
  {question:"The Battle of Khandaq is also known as the Battle of:",options:["The Trench","Badr","Uhud","Hunayn"],answer:0},
  {question:"The treaty between the Muslims and Quraysh was called:",options:["Treaty of Hudaybiyyah","Treaty of Badr","Treaty of Uhud","Treaty of Madinah"],answer:0},
  {question:"The first wife of Prophet Muhammad was:",options:["Khadijah","Aisha","Hafsa","Fatimah"],answer:0},
  {question:"The Prophet's daughter married to Ali was:",options:["Fatimah","Aisha","Zaynab","Ruqayyah"],answer:0},
  {question:"The Prophet's companion who accompanied him during Hijrah was:",options:["Abu Bakr","Umar","Uthman","Ali"],answer:0},
  {question:"The first Mu'adhdhin of Islam was:",options:["Bilal ibn Rabah","Abu Bakr","Umar","Salman"],answer:0},
  {question:"Adhan is the:",options:["Call to prayer","Friday sermon","Pilgrimage","Charity"],answer:0},
  {question:"The Friday congregational prayer is called:",options:["Jumu'ah","Tarawih","Tahajjud","Eid"],answer:0},
  {question:"The sermon delivered during Friday prayer is called:",options:["Khutbah","Adhan","Iqamah","Salah"],answer:0},
  {question:"The leader of congregational prayer is the:",options:["Imam","Mu'adhdhin","Qadi","Caliph"],answer:0},
  {question:"A person who judges according to Islamic law is a:",options:["Qadi","Mu'adhdhin","Imam","Caliph"],answer:0},
  {question:"Islamic law is commonly known as:",options:["Shariah","Sunnah","Hadith","Tafsir"],answer:0},
  {question:"Tafsir means:",options:["Interpretation or explanation of the Qur'an","Prayer","Fasting","Pilgrimage"],answer:0},
  {question:"Ummah refers to the:",options:["Muslim community","Mosque","Qur'an","Caliphate"],answer:0},
  {question:"The Night of Power is called:",options:["Laylat al-Qadr","Laylat al-Miraj","Ashura","Mawlid"],answer:0},
  {question:"Laylat al-Qadr occurs during:",options:["Ramadan","Muharram","Shawwal","Dhul-Hijjah"],answer:0},
  {question:"The Islamic New Year begins with:",options:["Muharram","Ramadan","Shawwal","Rajab"],answer:0},
  {question:"The first month of the Islamic calendar is:",options:["Muharram","Ramadan","Safar","Shawwal"],answer:0}
];

q["History"] = [
  {question:"History is the study of:",options:["Past human events","Future predictions only","Weather only","Mathematics"],answer:0},
  {question:"Archaeology studies the past mainly through:",options:["Material remains","Weather reports","Modern elections","Stock prices"],answer:0},
  {question:"A primary source is:",options:["Evidence from the period being studied","A modern summary only","A fictional story","A school timetable"],answer:0},
  {question:"An oral tradition is transmitted mainly by:",options:["Word of mouth","Printed newspapers only","Maps","Buildings"],answer:0},
  {question:"The Nok culture is associated with ancient:",options:["Nigeria","Egypt","Ghana","Morocco"],answer:0},
  {question:"The Nok people were famous for their:",options:["Terracotta sculptures and ironworking","Pyramids","Silk production","Shipbuilding"],answer:0},
  {question:"The ancient city of Kano became important in:",options:["Trans-Saharan trade","Atlantic slavery only","European industrialization","Roman conquest"],answer:0},
  {question:"The Hausa city-states were located mainly in:",options:["Northern Nigeria","Southern Ghana","Coastal Senegal","Eastern Congo"],answer:0},
  {question:"The Oyo Empire was located mainly in present-day:",options:["Southwestern Nigeria","Northern Cameroon","Eastern Nigeria","Southern Sudan"],answer:0},
  {question:"The traditional ruler of Oyo was known as the:",options:["Alaafin","Oba of Benin","Emir","Sultan"],answer:0},
  {question:"The Benin Kingdom was famous for its:",options:["Bronze works","Pyramids","Silk roads","Stonehenge"],answer:0},
  {question:"The ruler of the ancient Benin Kingdom was called the:",options:["Oba","Alaafin","Emir","Eze"],answer:0},
  {question:"The trans-Saharan trade connected West Africa with:",options:["North Africa","South America","Australia","East Asia"],answer:0},
  {question:"A major commodity traded from West Africa across the Sahara was:",options:["Gold","Tea","Coffee","Silk"],answer:0},
  {question:"The trans-Atlantic slave trade involved the forced movement of:",options:["Africans to the Americas","Europeans to Africa","Asians to Europe","Americans to Asia"],answer:0},
  {question:"The triangular trade connected Europe, Africa and:",options:["The Americas","Australia","India","China"],answer:0},
  {question:"European coastal trading posts in West Africa were commonly called:",options:["Factories","Universities","Parliaments","Capitals"],answer:0},
  {question:"Christian missionaries became active in West Africa mainly during the:",options:["19th century","12th century","5th century","15th century"],answer:0},
  {question:"The explorer associated with opening the Niger River region to British interest was:",options:["Mungo Park","Christopher Columbus","Marco Polo","Vasco da Gama"],answer:0},
  {question:"The Royal Niger Company was associated with:",options:["British commercial activities in Nigeria","French rule in Senegal","Portuguese rule in Angola","German rule in Cameroon"],answer:0},
  {question:"The amalgamation of Northern and Southern Nigeria occurred in:",options:["1914","1900","1960","1945"],answer:0},
  {question:"The first Governor-General of amalgamated Nigeria was:",options:["Lord Frederick Lugard","Lord Lyttleton","Nnamdi Azikiwe","Herbert Macaulay"],answer:0},
  {question:"Nigeria gained independence from Britain in:",options:["1960","1957","1963","1970"],answer:0},
  {question:"Nigeria became a republic in:",options:["1963","1960","1979","1999"],answer:0},
  {question:"Nigeria's first Prime Minister was:",options:["Abubakar Tafawa Balewa","Nnamdi Azikiwe","Obafemi Awolowo","Ahmadu Bello"],answer:0},
  {question:"Nigeria's first President was:",options:["Nnamdi Azikiwe","Tafawa Balewa","Obafemi Awolowo","Ahmadu Bello"],answer:0},
  {question:"The first military coup in Nigeria occurred in:",options:["1966","1960","1975","1983"],answer:0},
  {question:"Nigeria's civil war lasted from:",options:["1967 to 1970","1960 to 1963","1975 to 1979","1983 to 1985"],answer:0},
  {question:"The Nigerian Civil War is also known as the:",options:["Biafran War","Niger War","Northern War","Western War"],answer:0},
  {question:"Biafra was associated mainly with:",options:["The secession of Eastern Nigeria","Northern Nigeria","Western Nigeria","Lagos only"],answer:0},
  {question:"The leader of Biafra during the civil war was:",options:["Odumegwu Ojukwu","Yakubu Gowon","Nnamdi Azikiwe","Tafawa Balewa"],answer:0},
  {question:"Nigeria's civil war ended in:",options:["1970","1967","1975","1980"],answer:0},
  {question:"The policy used by the federal government during the civil war was popularly associated with:",options:["Reconstruction, Rehabilitation and Reconciliation","One Nigeria only","Economic isolation","Regional separation"],answer:0},
  {question:"The Organisation of African Unity was founded in:",options:["1963","1960","1975","1985"],answer:0},
  {question:"The OAU was later replaced by the:",options:["African Union","ECOWAS","United Nations","Commonwealth"],answer:0},
  {question:"The African Union was launched in:",options:["2002","1990","1963","2010"],answer:0},
  {question:"ECOWAS was established to promote:",options:["Economic cooperation in West Africa","Military rule","Colonialism","European integration"],answer:0},
  {question:"ECOWAS was established in:",options:["1975","1963","1985","1999"],answer:0},
  {question:"The headquarters of the African Union is in:",options:["Addis Ababa","Lagos","Accra","Abuja"],answer:0},
  {question:"The headquarters of ECOWAS is in:",options:["Abuja","Lagos","Accra","Dakar"],answer:0},
  {question:"The United Nations was established in:",options:["1945","1919","1939","1960"],answer:0},
  {question:"The League of Nations was established after:",options:["World War I","World War II","The Cold War","The Nigerian Civil War"],answer:0},
  {question:"World War I lasted from:",options:["1914 to 1918","1939 to 1945","1900 to 1910","1920 to 1925"],answer:0},
  {question:"World War II lasted from:",options:["1939 to 1945","1914 to 1918","1945 to 1950","1929 to 1935"],answer:0},
  {question:"The Cold War was mainly a rivalry between:",options:["The United States and Soviet Union","Britain and France","Nigeria and Ghana","China and Japan"],answer:0},
  {question:"The Berlin Wall fell in:",options:["1989","1979","1999","1961"],answer:0},
  {question:"The Soviet Union dissolved in:",options:["1991","1989","1975","2001"],answer:0},
  {question:"The industrial revolution began in:",options:["Britain","Nigeria","Egypt","Brazil"],answer:0},
  {question:"The French Revolution began in:",options:["1789","1776","1815","1914"],answer:0},
  {question:"The American Declaration of Independence was adopted in:",options:["1776","1789","1812","1865"],answer:0},
  {question:"The Berlin Conference on Africa took place in:",options:["1884-1885","1900-1901","1914-1918","1960-1961"],answer:0},
  {question:"The Berlin Conference was mainly concerned with:",options:["European partition of Africa","African independence","World War II","Trade unions"],answer:0},
  {question:"Indirect rule in Nigeria was strongly associated with:",options:["Lord Lugard","Mungo Park","Nnamdi Azikiwe","Herbert Macaulay"],answer:0},
  {question:"Indirect rule relied heavily on:",options:["Existing traditional rulers","European soldiers only","Missionaries only","Students"],answer:0},
  {question:"The Nigerian National Democratic Party was founded by:",options:["Herbert Macaulay","Nnamdi Azikiwe","Ahmadu Bello","Obafemi Awolowo"],answer:0},
  {question:"The NCNC was associated with:",options:["Nnamdi Azikiwe","Lord Lugard","Mungo Park","Yakubu Gowon"],answer:0},
  {question:"The Action Group was associated with:",options:["Obafemi Awolowo","Nnamdi Azikiwe","Tafawa Balewa","Ahmadu Bello"],answer:0},
  {question:"The Northern People's Congress was associated with:",options:["Ahmadu Bello","Obafemi Awolowo","Nnamdi Azikiwe","Herbert Macaulay"],answer:0},
  {question:"Nigeria became a member of the Commonwealth after:",options:["Independence","The civil war","The 1966 coup","Amalgamation"],answer:0}
];

fs.writeFileSync(
  './questions.js',
  'const questionBank = ' + JSON.stringify(q, null, 2) +
  ';\n\nmodule.exports = questionBank;\n'
);

console.log("IRS:", q["Islamic Religious Studies"].length);
console.log("History:", q["History"].length);
