const fs = require('fs');

const q = require('./questions');

function add(subject, questions) {
  q[subject] = [...(q[subject] || []), ...questions];
}

const physics = [
  ["The SI unit of force is:", ["Joule", "Newton", "Watt", "Pascal"], 1],
  ["The SI unit of work is:", ["Newton", "Joule", "Watt", "Volt"], 1],
  ["The SI unit of power is:", ["Watt", "Joule", "Newton", "Ohm"], 0],
  ["Speed is defined as:", ["Distance × time", "Distance / time", "Time / distance", "Mass / volume"], 1],
  ["Acceleration is the rate of change of:", ["Distance", "Speed", "Velocity", "Mass"], 2],
  ["The instrument used to measure electric current is:", ["Voltmeter", "Ammeter", "Barometer", "Thermometer"], 1],
  ["The instrument used to measure potential difference is:", ["Ammeter", "Voltmeter", "Galvanometer", "Hydrometer"], 1],
  ["Which quantity has both magnitude and direction?", ["Mass", "Speed", "Distance", "Velocity"], 3],
  ["The force that pulls objects toward Earth is:", ["Friction", "Gravity", "Magnetism", "Tension"], 1],
  ["Friction generally acts:", ["In the direction of motion", "Opposite motion", "Vertically upward", "Randomly"], 1],
  ["Density is:", ["Mass × volume", "Mass / volume", "Volume / mass", "Mass + volume"], 1],
  ["The SI unit of density is:", ["kg/m³", "g/cm", "kg/m", "N/m"], 0],
  ["A device that converts electrical energy to mechanical energy is:", ["Motor", "Generator", "Transformer", "Cell"], 0],
  ["A generator converts:", ["Mechanical energy to electrical energy", "Electrical to heat", "Heat to sound", "Light to mechanical"], 0],
  ["The energy possessed by a moving body is:", ["Potential", "Kinetic", "Chemical", "Nuclear"], 1],
  ["Stored energy due to position is:", ["Kinetic", "Potential", "Sound", "Electrical"], 1],
  ["The unit of frequency is:", ["Hertz", "Newton", "Joule", "Tesla"], 0],
  ["Sound cannot travel through:", ["Air", "Water", "Steel", "Vacuum"], 3],
  ["Light travels fastest through:", ["Glass", "Water", "Vacuum", "Diamond"], 2],
  ["The bouncing back of light is called:", ["Refraction", "Reflection", "Diffraction", "Dispersion"], 1],
  ["The bending of light when it enters another medium is:", ["Reflection", "Refraction", "Interference", "Polarization"], 1],
  ["A convex lens is generally:", ["Converging", "Diverging", "Opaque", "Flat"], 0],
  ["A concave lens is generally:", ["Converging", "Diverging", "Reflecting", "Transparent only"], 1],
  ["The colour with the longest wavelength in visible light is:", ["Violet", "Blue", "Green", "Red"], 3],
  ["The colour with the shortest wavelength is:", ["Red", "Yellow", "Violet", "Orange"], 2],
  ["Heat transfer through solids mainly occurs by:", ["Conduction", "Convection", "Radiation", "Evaporation"], 0],
  ["Heat transfer through fluids mainly occurs by:", ["Conduction", "Convection", "Reflection", "Radiation only"], 1],
  ["Heat from the Sun reaches Earth mainly by:", ["Conduction", "Convection", "Radiation", "Diffusion"], 2],
  ["The boiling point of pure water at standard pressure is:", ["0°C", "50°C", "100°C", "212°C only"], 2],
  ["The freezing point of pure water is:", ["0°C", "10°C", "50°C", "100°C"], 0],
  ["Ohm's law is expressed as:", ["V = IR", "P = VI", "F = ma", "W = mg"], 0],
  ["Resistance is measured in:", ["Volt", "Ampere", "Ohm", "Watt"], 2],
  ["Electrical power is given by:", ["P = VI", "P = IR", "P = V/R", "P = I/R"], 0],
  ["A transformer works with:", ["Direct current only", "Alternating current", "Static charge", "Chemical energy"], 1],
  ["A fuse is used mainly to:", ["Increase voltage", "Protect a circuit", "Store charge", "Measure current"], 1],
  ["The Earth behaves approximately like a:", ["Bar magnet", "Glass rod", "Battery", "Capacitor"], 0],
  ["Like magnetic poles:", ["Attract", "Repel", "Disappear", "Rotate"], 1],
  ["The unit of magnetic flux density is:", ["Tesla", "Weber", "Henry", "Farad"], 0],
  ["The force opposing motion between surfaces is:", ["Gravity", "Friction", "Upthrust", "Weight"], 1],
  ["Pressure is defined as:", ["Force / area", "Force × area", "Area / force", "Mass / area"], 0],
  ["The SI unit of pressure is:", ["Pascal", "Newton", "Joule", "Watt"], 0],
  ["Upthrust on an immersed body is related to:", ["Archimedes' principle", "Ohm's law", "Hooke's law", "Boyle's law"], 0],
  ["The tendency of a body to resist change in motion is:", ["Momentum", "Inertia", "Impulse", "Pressure"], 1],
  ["Momentum is:", ["Mass × velocity", "Mass / velocity", "Force × distance", "Power × time"], 0],
  ["The unit of momentum is:", ["kg m/s", "N/m", "J/s", "kg/m³"], 0],
  ["Newton's first law is also called the law of:", ["Acceleration", "Inertia", "Action", "Energy"], 1],
  ["Newton's third law concerns:", ["Equal and opposite forces", "Mass and volume", "Heat and work", "Pressure and area"], 0],
  ["The acceleration due to gravity near Earth's surface is approximately:", ["1.8 m/s²", "5.0 m/s²", "9.8 m/s²", "20 m/s²"], 2],
  ["A simple pendulum's period mainly depends on its:", ["Length", "Mass only", "Colour", "Material only"], 0],
  ["A wave transfers:", ["Matter only", "Energy", "Mass permanently", "Nothing"], 1],
  ["The distance between two successive crests is called:", ["Amplitude", "Frequency", "Wavelength", "Period"], 2],
  ["The maximum displacement of a wave is:", ["Amplitude", "Wavelength", "Frequency", "Speed"], 0],
  ["The number of oscillations per second is:", ["Period", "Frequency", "Amplitude", "Wavelength"], 1],
  ["A material that allows electric current easily is a:", ["Conductor", "Insulator", "Dielectric", "Semiconductor only"], 0],
  ["Rubber is generally an:", ["Conductor", "Insulator", "Electrolyte", "Magnet"], 1],
  ["A battery converts chemical energy into:", ["Electrical energy", "Sound energy", "Nuclear energy", "Gravitational energy"], 0],
  ["The unit of electric charge is:", ["Coulomb", "Volt", "Ohm", "Tesla"], 0],
  ["The unit of capacitance is:", ["Farad", "Henry", "Weber", "Coulomb"], 0],
  ["A change from liquid to gas is called:", ["Condensation", "Vaporization", "Freezing", "Melting"], 1],
  ["A change from gas to liquid is called:", ["Condensation", "Sublimation", "Melting", "Fusion"], 0]
];

const chemistry = [
  ["The chemical symbol for oxygen is:", ["O", "Ox", "Og", "C"], 0],
  ["The chemical symbol for sodium is:", ["So", "S", "Na", "N"], 2],
  ["The chemical symbol for potassium is:", ["P", "K", "Pt", "Po"], 1],
  ["The atomic number of hydrogen is:", ["1", "2", "8", "10"], 0],
  ["The atomic number of carbon is:", ["4", "6", "8", "12"], 1],
  ["The atomic number of oxygen is:", ["6", "7", "8", "16"], 2],
  ["Water has the formula:", ["CO₂", "H₂O", "O₂", "H₂"], 1],
  ["Carbon dioxide has the formula:", ["CO", "C₂O", "CO₂", "CaCO₃"], 2],
  ["Common salt is:", ["NaCl", "KCl", "NaOH", "HCl"], 0],
  ["An acid has a pH generally:", ["Above 7", "Equal to 14", "Below 7", "Equal to 7"], 2],
  ["A neutral solution has a pH of:", ["0", "5", "7", "14"], 2],
  ["A base turns red litmus:", ["Blue", "Green", "Yellow", "Black"], 0],
  ["An acid turns blue litmus:", ["Red", "Green", "Yellow", "White"], 0],
  ["The gas required for combustion is:", ["Nitrogen", "Oxygen", "Hydrogen", "Carbon dioxide"], 1],
  ["The most abundant gas in air is:", ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], 0],
  ["The process of losing electrons is:", ["Reduction", "Oxidation", "Neutralization", "Hydrolysis"], 1],
  ["The process of gaining electrons is:", ["Oxidation", "Reduction", "Combustion", "Ionization"], 1],
  ["A substance made of two or more elements chemically combined is a:", ["Mixture", "Compound", "Solution", "Suspension"], 1],
  ["Air is best described as a:", ["Compound", "Mixture", "Element", "Molecule"], 1],
  ["The smallest unit of an element that retains its properties is an:", ["Atom", "Ion", "Compound", "Mixture"], 0],
  ["A positively charged ion is called a:", ["Anion", "Cation", "Radical", "Electron"], 1],
  ["A negatively charged ion is called an:", ["Cation", "Anion", "Proton", "Atom"], 1],
  ["The charge on an electron is:", ["Positive", "Negative", "Neutral", "Variable"], 1],
  ["The charge on a proton is:", ["Negative", "Positive", "Neutral", "Zero"], 1],
  ["Neutrons have:", ["Positive charge", "Negative charge", "No charge", "Double charge"], 2],
  ["The nucleus contains:", ["Electrons only", "Protons and neutrons", "Neutrons and electrons", "Electrons and protons only"], 1],
  ["The periodic table is arranged mainly according to:", ["Atomic number", "Colour", "Density", "Melting point"], 0],
  ["Group 18 elements are called:", ["Alkali metals", "Halogens", "Noble gases", "Transition metals"], 2],
  ["Group 1 elements are called:", ["Alkali metals", "Noble gases", "Halogens", "Lanthanides"], 0],
  ["Group 17 elements are called:", ["Alkaline earth metals", "Halogens", "Noble gases", "Metalloids"], 1],
  ["The formula for methane is:", ["CH₄", "C₂H₆", "CH₃OH", "CO₂"], 0],
  ["The formula for ammonia is:", ["NH₃", "NO₂", "N₂O", "NH₄"], 0],
  ["The formula for hydrochloric acid is:", ["H₂SO₄", "HCl", "HNO₃", "NaOH"], 1],
  ["Sulfuric acid has the formula:", ["HCl", "H₂SO₄", "HNO₃", "H₂CO₃"], 1],
  ["The formula of calcium carbonate is:", ["CaO", "CaCO₃", "CaCl₂", "CaSO₄"], 1],
  ["A catalyst:", ["Is always consumed", "Speeds up a reaction", "Stops all reactions", "Changes products"], 1],
  ["An exothermic reaction:", ["Absorbs heat", "Releases heat", "Produces no energy", "Requires freezing"], 1],
  ["An endothermic reaction:", ["Releases heat", "Absorbs heat", "Produces only light", "Cannot occur"], 1],
  ["A solution contains a solute and a:", ["Catalyst", "Solvent", "Precipitate", "Gas"], 1],
  ["The substance being dissolved is the:", ["Solvent", "Solute", "Catalyst", "Indicator"], 1],
  ["Distillation separates substances mainly by differences in:", ["Colour", "Boiling points", "Mass only", "Density only"], 1],
  ["Filtration separates:", ["A soluble solid from water", "An insoluble solid from a liquid", "Two gases", "Two miscible liquids"], 1],
  ["Evaporation can be used to obtain:", ["Dissolved solid", "Gas only", "Insoluble solid only", "Metal only"], 0],
  ["A precipitate is a:", ["Gas formed", "Solid formed from a solution", "Liquid solvent", "Catalyst"], 1],
  ["Rusting of iron requires oxygen and:", ["Water", "Nitrogen", "Carbon dioxide only", "Salt only"], 0],
  ["The main metal in steel is:", ["Copper", "Iron", "Aluminium", "Zinc"], 1],
  ["Brass is mainly an alloy of copper and:", ["Iron", "Zinc", "Sodium", "Carbon"], 1],
  ["Bronze is mainly an alloy of copper and:", ["Tin", "Zinc", "Iron", "Aluminium"], 0],
  ["Organic chemistry mainly deals with compounds of:", ["Sodium", "Carbon", "Calcium", "Iron"], 1],
  ["Ethanol belongs to the family of:", ["Alcohols", "Alkanes", "Acids", "Esters"], 0],
  ["The functional group of alcohols is:", ["-COOH", "-OH", "-CHO", "-NH₂"], 1],
  ["The functional group of carboxylic acids is:", ["-OH", "-COOH", "-NH₂", "-Cl"], 1],
  ["Alkanes are:", ["Saturated hydrocarbons", "Unsaturated hydrocarbons", "Alcohols", "Acids"], 0],
  ["The simplest alkane is:", ["Methane", "Ethane", "Propane", "Butane"], 0],
  ["Ethene contains a:", ["Single bond only", "Double bond", "Triple bond", "Metallic bond"], 1],
  ["A reaction between an acid and a base is:", ["Neutralization", "Oxidation", "Cracking", "Polymerization"], 0],
  ["The gas produced when an acid reacts with a carbonate is:", ["Oxygen", "Hydrogen", "Carbon dioxide", "Nitrogen"], 2],
  ["The chemical formula of oxygen gas is:", ["O", "O₂", "O₃", "OH"], 1]
];

const biology = [
  ["The basic unit of life is the:", ["Tissue", "Organ", "Cell", "System"], 2],
  ["The organelle responsible for energy production is the:", ["Nucleus", "Mitochondrion", "Ribosome", "Vacuole"], 1],
  ["The control centre of a cell is the:", ["Nucleus", "Cell wall", "Cytoplasm", "Chloroplast"], 0],
  ["Photosynthesis occurs mainly in the:", ["Mitochondria", "Chloroplasts", "Ribosomes", "Nucleus"], 1],
  ["The green pigment in plants is:", ["Haemoglobin", "Chlorophyll", "Melanin", "Keratin"], 1],
  ["Plants absorb water mainly through their:", ["Leaves", "Roots", "Flowers", "Fruits"], 1],
  ["The organ that pumps blood is the:", ["Liver", "Heart", "Kidney", "Lung"], 1],
  ["The main function of red blood cells is to transport:", ["Hormones", "Oxygen", "Urine", "Bile"], 1],
  ["White blood cells help to:", ["Fight disease", "Digest food", "Carry oxygen", "Produce bile"], 0],
  ["Platelets are important for:", ["Blood clotting", "Breathing", "Digestion", "Vision"], 0],
  ["The liquid part of blood is:", ["Plasma", "Platelet", "Lymphocyte", "Haemoglobin"], 0],
  ["The organ mainly responsible for filtering blood and producing urine is the:", ["Heart", "Kidney", "Lung", "Stomach"], 1],
  ["The largest organ of the human body is the:", ["Liver", "Skin", "Heart", "Brain"], 1],
  ["The organ responsible for pumping oxygenated blood around the body is the:", ["Heart", "Kidney", "Liver", "Pancreas"], 0],
  ["Digestion begins in the:", ["Stomach", "Mouth", "Small intestine", "Large intestine"], 1],
  ["The enzyme in saliva that begins starch digestion is:", ["Pepsin", "Amylase", "Lipase", "Trypsin"], 1],
  ["Most nutrient absorption occurs in the:", ["Stomach", "Small intestine", "Large intestine", "Oesophagus"], 1],
  ["The large intestine mainly absorbs:", ["Water", "Protein", "Oxygen", "Bile"], 0],
  ["Bile is produced by the:", ["Pancreas", "Liver", "Kidney", "Stomach"], 1],
  ["The pancreas produces:", ["Digestive enzymes", "Urine", "Bile only", "Red blood cells"], 0],
  ["The respiratory organ in humans is the:", ["Kidney", "Lung", "Liver", "Skin"], 1],
  ["Gas exchange in the lungs occurs mainly in the:", ["Bronchi", "Alveoli", "Trachea", "Nose"], 1],
  ["The windpipe is called the:", ["Oesophagus", "Trachea", "Bronchiole", "Pharynx"], 1],
  ["The process by which green plants make food is:", ["Respiration", "Photosynthesis", "Transpiration", "Germination"], 1],
  ["Plants release which gas during photosynthesis?", ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"], 1],
  ["Plants take in which gas for photosynthesis?", ["Oxygen", "Carbon dioxide", "Hydrogen", "Nitrogen"], 1],
  ["The loss of water vapour from leaves is:", ["Respiration", "Transpiration", "Digestion", "Excretion"], 1],
  ["The tiny openings on leaves are called:", ["Stomata", "Villi", "Nephrons", "Lenticels"], 0],
  ["The male reproductive organ of a flower is the:", ["Carpel", "Stamen", "Ovary", "Sepal"], 1],
  ["The female reproductive part of a flower is the:", ["Stamen", "Carpel", "Anther", "Filament"], 1],
  ["Pollen grains are produced in the:", ["Stigma", "Anther", "Ovary", "Style"], 1],
  ["The transfer of pollen from anther to stigma is:", ["Fertilization", "Pollination", "Germination", "Dispersal"], 1],
  ["Fusion of male and female gametes is called:", ["Pollination", "Fertilization", "Germination", "Mitosis"], 1],
  ["The male gamete in humans is the:", ["Ovum", "Sperm", "Zygote", "Embryo"], 1],
  ["The female gamete in humans is the:", ["Sperm", "Ovum", "Zygote", "Embryo"], 1],
  ["The hormone responsible for male secondary sexual characteristics is mainly:", ["Oestrogen", "Testosterone", "Insulin", "Adrenaline"], 1],
  ["The hormone mainly associated with female secondary sexual characteristics is:", ["Testosterone", "Oestrogen", "Insulin", "Thyroxine"], 1],
  ["The genetic material in most living organisms is:", ["DNA", "Starch", "Fat", "Cellulose"], 0],
  ["The shape of DNA is commonly described as a:", ["Single ring", "Double helix", "Triangle", "Straight chain"], 1],
  ["Genes are located on:", ["Chromosomes", "Ribosomes", "Vacuoles", "Cell walls"], 0],
  ["A change in genetic material is called a:", ["Mutation", "Digestion", "Respiration", "Transpiration"], 0],
  ["The process of cell division producing two identical cells is:", ["Mitosis", "Meiosis", "Fertilization", "Mutation"], 0],
  ["Meiosis produces cells with:", ["Double chromosome number", "Half chromosome number", "No chromosomes", "Four times chromosomes"], 1],
  ["An organism that makes its own food is called a:", ["Heterotroph", "Autotroph", "Parasite", "Decomposer"], 1],
  ["An organism that obtains food from other organisms is a:", ["Autotroph", "Heterotroph", "Producer", "Chemosynthetic organism"], 1],
  ["Organisms that break down dead organic matter are:", ["Producers", "Decomposers", "Consumers", "Predators"], 1],
  ["A sequence showing feeding relationships is a:", ["Food chain", "Habitat", "Niche", "Population"], 0],
  ["The natural home of an organism is its:", ["Habitat", "Community", "Population", "Biome"], 0],
  ["All organisms of the same species in an area form a:", ["Population", "Community", "Habitat", "Ecosystem"], 0],
  ["A group of different populations living together is a:", ["Species", "Community", "Gene", "Tissue"], 1],
  ["The living and non-living components interacting in an area form an:", ["Ecosystem", "Organ", "Population", "Organism"], 0],
  ["A relationship where both organisms benefit is:", ["Parasitism", "Mutualism", "Predation", "Competition"], 1],
  ["A relationship where one benefits and the other is harmed is:", ["Mutualism", "Parasitism", "Commensalism", "Cooperation"], 1],
  ["An example of a vertebrate is:", ["Earthworm", "Fish", "Snail", "Cockroach"], 1],
  ["Animals without backbones are called:", ["Vertebrates", "Invertebrates", "Mammals", "Amphibians"], 1],
  ["Mammals generally possess:", ["Feathers", "Mammary glands", "Scales only", "Gills"], 1],
  ["Birds are characterized by having:", ["Feathers", "Fins", "Fur", "Gills"], 0],
  ["Fish mainly breathe using:", ["Lungs", "Gills", "Skin only", "Trachea"], 1],
  ["Amphibians can generally live:", ["Only in deserts", "In water and on land", "Only in trees", "Only underground"], 1],
  ["The process of maintaining a stable internal environment is:", ["Homeostasis", "Evolution", "Mutation", "Pollination"], 0]
];

function convert(rows) {
  return rows.map(([question, options, answer]) => ({
    question,
    options,
    answer
  }));
}

add("Physics", convert(physics));
add("Chemistry", convert(chemistry));
add("Biology", convert(biology));

fs.writeFileSync(
  './questions.js',
  'const questionBank = ' +
  JSON.stringify(q, null, 2) +
  ';\n\nmodule.exports = questionBank;\n'
);

console.log("Physics:", q.Physics.length);
console.log("Chemistry:", q.Chemistry.length);
console.log("Biology:", q.Biology.length);
