const fs = require('fs');
const q = require('./questions');

q["Igbo"] = [
  {question:"Kedu ihe 'Ndewo' pụtara?",options:["Hello","Goodbye","Thank you","Sorry"],answer:0},
  {question:"Kedu ihe 'Daalụ' pụtara?",options:["Thank you","Hello","Good night","Come here"],answer:0},
  {question:"Kedu ihe 'Biko' pụtara?",options:["Please","Thank you","Yes","No"],answer:0},
  {question:"Kedu ihe 'Ee' pụtara?",options:["Yes","No","Maybe","Please"],answer:0},
  {question:"Kedu ihe 'Mba' pụtara?",options:["No","Yes","Thank you","Welcome"],answer:0},
  {question:"'Nna' pụtara:",options:["Father","Mother","Brother","Sister"],answer:0},
  {question:"'Nne' pụtara:",options:["Mother","Father","Brother","Daughter"],answer:0},
  {question:"'Nwanne' pụtara:",options:["Sibling","Teacher","Farmer","Doctor"],answer:0},
  {question:"'Nwa' pụtara:",options:["Child","House","Food","Water"],answer:0},
  {question:"'Nwoke' pụtara:",options:["Man","Woman","Child","Girl"],answer:0},
  {question:"'Nwanyị' pụtara:",options:["Woman","Man","Boy","Father"],answer:0},
  {question:"'Nwaanyị' pụtara:",options:["Woman/Girl","Man","Boy","Father"],answer:0},
  {question:"'Nwa nwoke' pụtara:",options:["Boy","Girl","Mother","Sister"],answer:0},
  {question:"'Nwaanyị' can refer to:",options:["A female person","A male person","A house","A tree"],answer:0},
  {question:"'Ụlọ' pụtara:",options:["House","School","Market","River"],answer:0},
  {question:"'Ụlọ akwụkwọ' pụtara:",options:["School","Hospital","Church","Market"],answer:0},
  {question:"'Ahịa' pụtara:",options:["Market","House","Farm","River"],answer:0},
  {question:"'Ụlọ ọgwụ' pụtara:",options:["Hospital","School","Market","Church"],answer:0},
  {question:"'Ụka' pụtara:",options:["Church","School","House","Farm"],answer:0},
  {question:"'Osimiri' pụtara:",options:["River","Mountain","Forest","Road"],answer:0},
  {question:"'Mmiri' pụtara:",options:["Water","Food","Fire","Air"],answer:0},
  {question:"'Ọkụ' pụtara:",options:["Fire","Water","Food","House"],answer:0},
  {question:"'Ala' pụtara:",options:["Land","Water","Sky","Fire"],answer:0},
  {question:"'Igwe' can mean:",options:["Sky","Water","Food","House"],answer:0},
  {question:"'Anyanwụ' pụtara:",options:["Sun","Moon","Star","Rain"],answer:0},
  {question:"'Ọnwa' pụtara:",options:["Moon","Sun","Star","Cloud"],answer:0},
  {question:"'Kpakpando' pụtara:",options:["Star","Sun","Moon","Rain"],answer:0},
  {question:"'Mmiri ozuzo' pụtara:",options:["Rain","Sunlight","Wind","Cloud"],answer:0},
  {question:"'Ifufe' pụtara:",options:["Wind","Rain","Fire","Water"],answer:0},
  {question:"'Osisi' pụtara:",options:["Tree","House","Road","Animal"],answer:0},
  {question:"'Okooko' pụtara:",options:["Flower","Tree","Fruit","Leaf"],answer:0},
  {question:"'Akwụkwọ' can mean:",options:["Book or leaf","House","Water","Road"],answer:0},
  {question:"'Mkpụrụ' pụtara:",options:["Fruit/seed","Water","House","Cloth"],answer:0},
  {question:"'Ji' pụtara:",options:["Yam","Rice","Beans","Fish"],answer:0},
  {question:"'Osikapa' pụtara:",options:["Rice","Yam","Cassava","Maize"],answer:0},
  {question:"'Agwa' pụtara:",options:["Beans","Rice","Yam","Meat"],answer:0},
  {question:"'Ọka' pụtara:",options:["Maize","Yam","Beans","Fish"],answer:0},
  {question:"'Akwụkwọ nri' pụtara:",options:["Vegetable","Fruit","Meat","Fish"],answer:0},
  {question:"'Anụ' pụtara:",options:["Meat/animal","Water","Rice","Vegetable"],answer:0},
  {question:"'Azụ' pụtara:",options:["Fish","Meat","Chicken","Goat"],answer:0},
  {question:"'Okuko' pụtara:",options:["Chicken","Goat","Cow","Fish"],answer:0},
  {question:"'Ewu' pụtara:",options:["Goat","Sheep","Cow","Chicken"],answer:0},
  {question:"'Ehi' pụtara:",options:["Cow","Goat","Dog","Fish"],answer:0},
  {question:"'Nkịta' pụtara:",options:["Dog","Cat","Goat","Bird"],answer:0},
  {question:"'Pusi' pụtara:",options:["Cat","Dog","Cow","Chicken"],answer:0},
  {question:"'Ụgbọala' pụtara:",options:["Car","House","Bicycle","Boat"],answer:0},
  {question:"'Ụgbọ ịnyịnya' refers to:",options:["Vehicle/cart","House","Farm","River"],answer:0},
  {question:"'Ụzọ' pụtara:",options:["Road/way","House","Market","Food"],answer:0},
  {question:"'Aka' pụtara:",options:["Hand","Leg","Head","Eye"],answer:0},
  {question:"'Ụkwụ' pụtara:",options:["Leg/foot","Hand","Head","Ear"],answer:0},
  {question:"'Isi' pụtara:",options:["Head","Hand","Eye","Mouth"],answer:0},
  {question:"'Anya' pụtara:",options:["Eye","Ear","Nose","Mouth"],answer:0},
  {question:"'Ntị' pụtara:",options:["Ear","Eye","Hand","Leg"],answer:0},
  {question:"'Ọnụ' pụtara:",options:["Mouth","Nose","Eye","Ear"],answer:0},
  {question:"'Imi' pụtara:",options:["Nose","Mouth","Eye","Ear"],answer:0},
  {question:"'Nri' pụtara:",options:["Food","Water","House","Clothing"],answer:0},
  {question:"'Uwe' pụtara:",options:["Clothes","Food","Water","House"],answer:0},
  {question:"'Ego' pụtara:",options:["Money","Food","Water","House"],answer:0},
  {question:"'Akwụkwọ' in school context usually means:",options:["Book","Money","House","Food"],answer:0},
  {question:"'Onye nkuzi' pụtara:",options:["Teacher","Student","Doctor","Farmer"],answer:0},
  {question:"'Nwa akwụkwọ' pụtara:",options:["Student","Teacher","Doctor","Farmer"],answer:0},
  {question:"'Dọkịta' pụtara:",options:["Doctor","Teacher","Farmer","Driver"],answer:0},
  {question:"'Ọrụ' pụtara:",options:["Work","Food","House","Water"],answer:0}
];

fs.writeFileSync(
  './questions.js',
  'const questionBank = ' + JSON.stringify(q, null, 2) +
  ';\n\nmodule.exports = questionBank;\n'
);

console.log("Igbo:", q["Igbo"].length);
