const fs = require('fs');
const q = require('./questions');

q["Government"] = [
  {question:"Government is the machinery through which a state is:",options:["Governed","Destroyed","Sold","Privatized"],answer:0},
  {question:"Which of the following is an essential element of a state?",options:["Sovereignty","A political party","A market","A newspaper"],answer:0},
  {question:"Sovereignty means:",options:["Supreme authority","Population growth","Economic wealth","Military training"],answer:0},
  {question:"Democracy is government by:",options:["The people","The military","Judges","Traditional rulers"],answer:0},
  {question:"A constitution is a:",options:["Set of fundamental rules of government","Political party","Tax document","Court building"],answer:0},
  {question:"The legislature is mainly responsible for:",options:["Making laws","Interpreting laws","Enforcing laws","Conducting censuses"],answer:0},
  {question:"The executive is mainly responsible for:",options:["Implementing laws","Interpreting laws","Writing textbooks","Conducting examinations"],answer:0},
  {question:"The judiciary is mainly responsible for:",options:["Interpreting laws","Collecting taxes","Making budgets","Running elections"],answer:0},
  {question:"Separation of powers means:",options:["Division of governmental powers among organs","Rule by one person","Military control","Abolition of courts"],answer:0},
  {question:"Checks and balances are designed to:",options:["Prevent abuse of power","End elections","Increase dictatorship","Remove the legislature"],answer:0},
  {question:"A federal system divides powers between:",options:["Central and component governments","Political parties","Courts and schools","Businesses and families"],answer:0},
  {question:"A unitary system gives greater constitutional authority to the:",options:["Central government","Local government","Political parties","Traditional rulers"],answer:0},
  {question:"A bicameral legislature has:",options:["Two chambers","One chamber","Three chambers","Four chambers"],answer:0},
  {question:"A unicameral legislature has:",options:["One chamber","Two chambers","Three chambers","Four chambers"],answer:0},
  {question:"The upper chamber of a legislature is commonly called the:",options:["Senate","Cabinet","Court","Council"],answer:0},
  {question:"A referendum is:",options:["A direct vote by citizens on an issue","A court judgment","A cabinet meeting","A tax payment"],answer:0},
  {question:"Universal adult suffrage means:",options:["Eligible adults have the right to vote","Only soldiers vote","Only rulers vote","Children vote"],answer:0},
  {question:"An election is a process of:",options:["Choosing representatives","Making court judgments","Collecting taxes","Writing constitutions only"],answer:0},
  {question:"A political party mainly seeks to:",options:["Gain political power","Avoid elections","Control the courts","Abolish government"],answer:0},
  {question:"An opposition party is one that:",options:["Challenges the ruling party","Controls the army","Runs the judiciary","Has no members"],answer:0},
  {question:"A pressure group mainly seeks to:",options:["Influence government policy","Form a government in every case","Conduct elections","Replace the constitution"],answer:0},
  {question:"Public opinion refers to:",options:["Views held by members of the public","Government revenue","Court decisions","Military orders"],answer:0},
  {question:"Citizenship means:",options:["Legal membership of a state","Owning a business","Living in a hotel","Working for government"],answer:0},
  {question:"The right to vote is known as:",options:["Franchise","Veto","Immunity","Sovereignty"],answer:0},
  {question:"The rule of law means:",options:["Everyone is subject to the law","Leaders are above the law","Only judges obey laws","Citizens make all laws"],answer:0},
  {question:"Fundamental human rights include the right to:",options:["Life","Steal","Harm others","Break laws"],answer:0},
  {question:"A bill is:",options:["A proposed law","A court judgment","A tax receipt","An election result"],answer:0},
  {question:"A bill becomes law after:",options:["Passing the required legislative process","Being mentioned on television","Being proposed by one citizen","Being printed in a newspaper"],answer:0},
  {question:"Veto power means the power to:",options:["Reject or prevent a measure","Conduct elections","Collect taxes","Appoint every citizen"],answer:0},
  {question:"A coup d'état is:",options:["An unconstitutional seizure of government","A peaceful election","A referendum","A court ruling"],answer:0},
  {question:"Military rule is government by:",options:["Armed forces","Judges","Students","Businesses"],answer:0},
  {question:"Colonialism involves:",options:["Control of one territory by another power","Equal partnership between states","Local elections","Free trade only"],answer:0},
  {question:"Nationalism emphasizes:",options:["National identity and self-determination","Foreign control","Military dictatorship","Economic isolation"],answer:0},
  {question:"A political ideology is:",options:["A set of ideas about politics and society","A tax receipt","A court document","A census form"],answer:0},
  {question:"Liberalism generally emphasizes:",options:["Individual liberty","Absolute monarchy","Military rule","One-party dictatorship"],answer:0},
  {question:"Socialism generally emphasizes:",options:["Social and economic equality","Absolute private monopoly","Military government","No public services"],answer:0},
  {question:"Capitalism is characterized by:",options:["Private ownership and market activity","Complete state ownership","No private property","No markets"],answer:0},
  {question:"A monarchy is a system in which the head of state is:",options:["A monarch","Always a president","Always a judge","A military officer"],answer:0},
  {question:"A constitutional monarchy is one in which:",options:["The monarch's powers are limited by constitutional rules","The monarch has unlimited power","There is no constitution","The military rules"],answer:0},
  {question:"An absolute monarchy gives the monarch:",options:["Extensive political power","No authority","Only judicial power","Only ceremonial duties"],answer:0},
  {question:"Anarchy refers to:",options:["Absence of effective government or authority","Strong democracy","Federalism","Parliamentary government"],answer:0},
  {question:"A civil servant is generally:",options:["A permanent government employee","An elected politician","A private trader","A traditional ruler"],answer:0},
  {question:"The civil service is expected to be:",options:["Politically neutral and professional","A political party","A military unit","A pressure group"],answer:0},
  {question:"Local government is the level of government closest to:",options:["The people","Foreign governments","International organizations","Federal courts"],answer:0},
  {question:"Decentralization involves:",options:["Transferring powers away from the centre","Centralizing all powers","Ending elections","Removing local authorities"],answer:0},
  {question:"Political participation includes:",options:["Voting","Breaking laws","Avoiding all civic activity","Destroying institutions"],answer:0},
  {question:"Political socialization is the process of:",options:["Learning political values and attitudes","Counting votes","Collecting taxes","Making court judgments"],answer:0},
  {question:"Diplomacy involves:",options:["Managing relations between states","Running local markets","Making school rules","Producing goods"],answer:0},
  {question:"Foreign policy refers to a state's:",options:["Approach to relations with other states","Domestic tax system","School curriculum","Local government structure"],answer:0},
  {question:"The United Nations was established mainly to promote:",options:["International peace and cooperation","Colonialism","Military dictatorship","Economic isolation"],answer:0},
  {question:"A constitution can be described as rigid when it:",options:["Requires a special procedure for amendment","Can be changed like an ordinary law","Has no written rules","Cannot contain rights"],answer:0},
  {question:"A flexible constitution can generally be amended:",options:["By the ordinary legislative process","Only by the military","Only by judges","Never"],answer:0},
  {question:"A written constitution is:",options:["Contained in formal documents","Based entirely on customs","Never recorded","Always unwritten"],answer:0},
  {question:"A referendum is an example of:",options:["Direct democracy","Military rule","Monarchy","Oligarchy"],answer:0},
  {question:"Oligarchy is government by:",options:["A small group","The whole population","One elected president","All judges"],answer:0},
  {question:"Aristocracy is traditionally government by:",options:["A privileged class","All citizens","Students","Workers only"],answer:0},
  {question:"A presidential system normally has a:",options:["President as head of government","Prime Minister as sole executive","Monarch as sole legislator","Chief Justice as head of government"],answer:0},
  {question:"In a parliamentary system, the head of government is usually the:",options:["Prime Minister","Chief Justice","Speaker","Monarch"],answer:0},
  {question:"The principle of popular sovereignty means:",options:["Ultimate political authority belongs to the people","The army owns the state","Judges make all decisions","Foreign governments control the state"],answer:0},
  {question:"A pressure group differs from a political party because it mainly aims to:",options:["Influence policy rather than form government","Win every election","Abolish government","Control the judiciary"],answer:0},
  {question:"Political apathy means:",options:["Lack of interest in political activities","Strong political participation","Military rule","Voting in every election"],answer:0}
];

q["Literature in English"] = [
  {question:"A literary work that tells a story through narration is mainly:",options:["Narrative","Exposition","Advertisement","Report"],answer:0},
  {question:"A poem is traditionally arranged in:",options:["Lines and stanzas","Chapters only","Paragraphs only","Acts only"],answer:0},
  {question:"A stanza in poetry is:",options:["A group of lines","A character","A plot","A title"],answer:0},
  {question:"The central idea of a literary work is its:",options:["Theme","Setting","Dialogue","Character"],answer:0},
  {question:"The time and place of a story constitute its:",options:["Setting","Plot","Theme","Conflict"],answer:0},
  {question:"The sequence of events in a story is the:",options:["Plot","Setting","Mood","Style"],answer:0},
  {question:"The people or figures in a story are called:",options:["Characters","Stanzas","Themes","Narrators"],answer:0},
  {question:"The main character in a story is the:",options:["Protagonist","Antagonist","Narrator","Spectator"],answer:0},
  {question:"The character who opposes the protagonist is the:",options:["Antagonist","Narrator","Speaker","Protagonist"],answer:0},
  {question:"A struggle between opposing forces is called:",options:["Conflict","Setting","Tone","Rhyme"],answer:0},
  {question:"A narrator who tells the story using 'I' is using:",options:["First-person narration","Third-person narration","Dramatic narration","Objective narration"],answer:0},
  {question:"A narrator who uses 'he', 'she' or 'they' commonly uses:",options:["Third-person narration","First-person narration","Second-person narration","Dialogue"],answer:0},
  {question:"A comparison using 'like' or 'as' is a:",options:["Simile","Metaphor","Irony","Pun"],answer:0},
  {question:"A direct comparison without 'like' or 'as' is a:",options:["Metaphor","Simile","Rhyme","Alliteration"],answer:0},
  {question:"Giving human qualities to non-human things is:",options:["Personification","Hyperbole","Irony","Satire"],answer:0},
  {question:"Deliberate exaggeration for effect is:",options:["Hyperbole","Metaphor","Alliteration","Onomatopoeia"],answer:0},
  {question:"Repetition of initial consonant sounds is:",options:["Alliteration","Assonance","Rhyme","Irony"],answer:0},
  {question:"Repetition of vowel sounds is:",options:["Assonance","Alliteration","Metaphor","Satire"],answer:0},
  {question:"A word that imitates a natural sound is an example of:",options:["Onomatopoeia","Irony","Paradox","Metaphor"],answer:0},
  {question:"A statement that appears self-contradictory but may contain truth is a:",options:["Paradox","Simile","Pun","Narrative"],answer:0},
  {question:"Irony occurs when:",options:["The intended meaning differs from the literal meaning","A story has no conflict","Every statement is true","A poem has no rhythm"],answer:0},
  {question:"Satire uses humour or ridicule mainly to:",options:["Criticize faults in society or individuals","Describe scenery only","Create rhyme","Introduce characters"],answer:0},
  {question:"A play is primarily written to be:",options:["Performed","Memorized only","Painted","Sung only"],answer:0},
  {question:"The written words spoken by characters in a play are:",options:["Dialogue","Narration","Setting","Stage directions"],answer:0},
  {question:"Instructions to actors in a play are called:",options:["Stage directions","Dialogue","Theme","Prologue"],answer:0},
  {question:"A play divided into major sections is divided into:",options:["Acts","Stanzas","Chapters","Paragraphs"],answer:0},
  {question:"A tragedy usually ends with:",options:["Serious suffering or downfall","A wedding celebration only","A joke","No conflict"],answer:0},
  {question:"A comedy usually aims to:",options:["Entertain through humour","Present only tragic events","Avoid characters","Eliminate dialogue"],answer:0},
  {question:"A tragic hero is usually:",options:["A significant character brought to downfall","A comic servant","A narrator only","A minor character"],answer:0},
  {question:"The tragic hero's weakness or error is called:",options:["Hamartia","Catharsis","Climax","Epilogue"],answer:0},
  {question:"Catharsis refers to:",options:["Emotional release experienced by the audience","The setting of a play","The opening scene","A character's name"],answer:0},
  {question:"A literary work that teaches a moral lesson through animals is a:",options:["Fable","Epic","Elegy","Sonnet"],answer:0},
  {question:"An extended narrative poem about heroic deeds is an:",options:["Epic","Elegy","Ode","Limerick"],answer:0},
  {question:"A poem mourning the dead is an:",options:["Elegy","Ode","Epic","Ballad"],answer:0},
  {question:"A poem expressing praise or serious reflection is an:",options:["Ode","Elegy","Fable","Farce"],answer:0},
  {question:"A fourteen-line poem is commonly called a:",options:["Sonnet","Ballad","Epic","Ode"],answer:0},
  {question:"A narrative poem that often tells a story in simple language is a:",options:["Ballad","Sonnet","Elegy","Ode"],answer:0},
  {question:"The attitude of a writer toward a subject is called:",options:["Tone","Plot","Setting","Conflict"],answer:0},
  {question:"The emotional atmosphere created by a literary work is its:",options:["Mood","Plot","Character","Dialogue"],answer:0},
  {question:"The choice of words used by a writer is called:",options:["Diction","Setting","Plot","Conflict"],answer:0},
  {question:"The distinctive manner in which a writer uses language is:",options:["Style","Theme","Setting","Character"],answer:0},
  {question:"A recurring image, idea or symbol in a work is a:",options:["Motif","Plot","Act","Dialogue"],answer:0},
  {question:"An object that represents a deeper meaning is a:",options:["Symbol","Narrator","Stanza","Setting"],answer:0},
  {question:"A story within a story is known as a:",options:["Frame narrative","Sonnet","Elegy","Aside"],answer:0},
  {question:"A speech by a character alone on stage revealing thoughts is a:",options:["Soliloquy","Dialogue","Aside","Prologue"],answer:0},
  {question:"A short remark intended to be heard by the audience but not other characters is an:",options:["Aside","Soliloquy","Epilogue","Act"],answer:0},
  {question:"The opening section of a literary work or play is sometimes called a:",options:["Prologue","Epilogue","Climax","Denouement"],answer:0},
  {question:"The concluding section of a literary work is sometimes called an:",options:["Epilogue","Prologue","Exposition","Aside"],answer:0},
  {question:"The highest point of tension in a plot is the:",options:["Climax","Exposition","Resolution","Setting"],answer:0},
  {question:"The introduction of characters and setting is called:",options:["Exposition","Climax","Denouement","Resolution"],answer:0},
  {question:"The final resolution of a conflict is called:",options:["Denouement","Exposition","Rising action","Foreshadowing"],answer:0},
  {question:"A hint of something that will happen later is:",options:["Foreshadowing","Flashback","Satire","Irony"],answer:0},
  {question:"A scene that moves back to an earlier time is a:",options:["Flashback","Foreshadowing","Climax","Prologue"],answer:0},
  {question:"A sudden change from a serious mood to a humorous one is called:",options:["Comic relief","Catharsis","Tragedy","Conflict"],answer:0},
  {question:"A literary device in which the opposite of what is expected happens is:",options:["Irony","Simile","Alliteration","Personification"],answer:0},
  {question:"A pun is based mainly on:",options:["A play on words","A long narrative","A tragic ending","A change of setting"],answer:0},
  {question:"A deliberate contrast between two ideas or characters is:",options:["Antithesis","Hyperbole","Onomatopoeia","Simile"],answer:0},
  {question:"A question asked for effect rather than an answer is a:",options:["Rhetorical question","Narrative question","Stage direction","Prologue"],answer:0},
  {question:"The repetition of a word or phrase at the beginning of successive lines is:",options:["Anaphora","Irony","Metaphor","Pun"],answer:0},
  {question:"The repetition of a word or phrase at the end of successive lines is:",options:["Epistrophe","Anaphora","Simile","Satire"],answer:0},
  {question:"The use of language to create pictures in the reader's mind is:",options:["Imagery","Plot","Dialogue","Conflict"],answer:0}
];

fs.writeFileSync(
  './questions.js',
  'const questionBank = ' + JSON.stringify(q, null, 2) +
  ';\n\nmodule.exports = questionBank;\n'
);

console.log("Government:", q["Government"].length);
console.log("Literature:", q["Literature in English"].length);
