const fs = require('fs');
const q = require('./questions');

q["Geography"] = [
  {question:"Geography is the study of:",options:["The Earth and its features","Only plants","Only animals","Only government"],answer:0},
  {question:"The shape of the Earth is approximately:",options:["Spherical","Flat","Square","Triangular"],answer:0},
  {question:"The imaginary line that divides Earth into Northern and Southern Hemispheres is the:",options:["Equator","Prime Meridian","Tropic of Cancer","Arctic Circle"],answer:0},
  {question:"The Prime Meridian passes through:",options:["Greenwich","Lagos","New York","Tokyo"],answer:0},
  {question:"Lines drawn east-west on maps are called:",options:["Latitudes","Longitudes","Contours","Bearings"],answer:0},
  {question:"Lines drawn north-south on maps are called:",options:["Longitudes","Latitudes","Contours","Isobars"],answer:0},
  {question:"The Tropic of Cancer is located at approximately:",options:["23.5°N","23.5°S","66.5°N","0°"],answer:0},
  {question:"The Tropic of Capricorn is located at approximately:",options:["23.5°S","23.5°N","66.5°S","0°"],answer:0},
  {question:"The Earth's rotation causes:",options:["Day and night","The seasons only","Tides only","Earthquakes"],answer:0},
  {question:"The Earth's revolution around the Sun takes approximately:",options:["365¼ days","24 hours","30 days","7 days"],answer:0},
  {question:"A map showing relief features is a:",options:["Topographic map","Political map","Weather map","Road map"],answer:0},
  {question:"A map scale shows the relationship between:",options:["Map distance and ground distance","Rainfall and temperature","Population and land","Height and pressure"],answer:0},
  {question:"A contour line joins places of equal:",options:["Elevation","Temperature","Rainfall","Population"],answer:0},
  {question:"Closely spaced contour lines indicate:",options:["Steep slopes","Gentle slopes","Flat land","A river"],answer:0},
  {question:"Widely spaced contour lines indicate:",options:["Gentle slopes","Steep slopes","Cliffs","Mountains only"],answer:0},
  {question:"A river's source is:",options:["Its beginning","Its mouth","Its delta","Its estuary"],answer:0},
  {question:"The mouth of a river is where it:",options:["Enters a sea, lake or another river","Begins","Forms a mountain","Changes direction"],answer:0},
  {question:"A delta is formed mainly by:",options:["Deposition of sediments","Volcanic eruption","Earthquake","Wind erosion only"],answer:0},
  {question:"An estuary is:",options:["A tidal river mouth","A mountain peak","A desert","A waterfall"],answer:0},
  {question:"Erosion is the:",options:["Wearing away and removal of materials","Formation of clouds","Growth of plants","Movement of planets"],answer:0},
  {question:"Weathering is the:",options:["Breakdown of rocks in place","Movement of rivers","Formation of oceans","Growth of forests"],answer:0},
  {question:"The wearing away of land by wind is common in:",options:["Deserts","Rainforests","Swamps","Polar oceans"],answer:0},
  {question:"A desert is characterized mainly by:",options:["Very low rainfall","Heavy rainfall","Dense forests","Permanent snow"],answer:0},
  {question:"The tropical rainforest is characterized by:",options:["High rainfall and dense vegetation","Very low rainfall","Permanent ice","Sparse vegetation"],answer:0},
  {question:"Savanna vegetation is mainly:",options:["Grass with scattered trees","Dense evergreen forest","Moss only","No vegetation"],answer:0},
  {question:"Climate refers to:",options:["Long-term atmospheric conditions","Today's weather only","A single storm","Wind direction only"],answer:0},
  {question:"Weather refers to:",options:["Short-term atmospheric conditions","Long-term climate patterns","Population distribution","Rock formation"],answer:0},
  {question:"An instrument used to measure temperature is a:",options:["Thermometer","Barometer","Rain gauge","Anemometer"],answer:0},
  {question:"An instrument used to measure atmospheric pressure is a:",options:["Barometer","Thermometer","Rain gauge","Wind vane"],answer:0},
  {question:"An instrument used to measure rainfall is a:",options:["Rain gauge","Barometer","Thermometer","Anemometer"],answer:0},
  {question:"An instrument used to measure wind speed is an:",options:["Anemometer","Barometer","Thermometer","Rain gauge"],answer:0},
  {question:"The layer of the atmosphere where most weather occurs is the:",options:["Troposphere","Stratosphere","Mesosphere","Thermosphere"],answer:0},
  {question:"The ozone layer is mainly found in the:",options:["Stratosphere","Troposphere","Mesosphere","Exosphere"],answer:0},
  {question:"A volcano is an opening through which:",options:["Magma and gases reach the surface","Rain falls","Rivers flow","Wind enters"],answer:0},
  {question:"An earthquake is caused by:",options:["Sudden movement within the Earth's crust","Heavy rainfall only","Wind erosion","Ocean tides only"],answer:0},
  {question:"A tsunami is commonly caused by:",options:["Undersea earthquakes","Desert winds","Heavy snowfall","Drought"],answer:0},
  {question:"Population density means:",options:["Number of people per unit area","Total number of houses","Number of cities","Birth rate only"],answer:0},
  {question:"A census is the official counting of:",options:["A population","Rivers","Mountains","Factories"],answer:0},
  {question:"Migration means:",options:["Movement of people from one place to another","Growth of crops","Movement of clouds","Flow of rivers"],answer:0},
  {question:"Urbanization refers to the:",options:["Growth of towns and cities","Growth of forests","Decline of cities","Formation of deserts"],answer:0},
  {question:"Agriculture is the:",options:["Cultivation of crops and rearing of animals","Mining of minerals only","Construction of roads","Manufacture of cars"],answer:0},
  {question:"Subsistence farming is mainly carried out to:",options:["Meet the farmer's needs","Produce only for export","Supply factories","Produce minerals"],answer:0},
  {question:"Commercial farming is mainly for:",options:["Sale and profit","Personal consumption only","Research only","Government employment"],answer:0},
  {question:"Plantation agriculture commonly involves:",options:["Large-scale production of cash crops","Small backyard gardens","Fishing only","Mining only"],answer:0},
  {question:"A cash crop is mainly grown for:",options:["Sale","Decoration","Animal shelter","Soil protection only"],answer:0},
  {question:"Examples of cash crops include:",options:["Cocoa and rubber","Maize only","Cassava only","Beans only"],answer:0},
  {question:"Mining involves the extraction of:",options:["Minerals from the Earth","Crops","Fish","Rainwater"],answer:0},
  {question:"Petroleum is classified as a:",options:["Fossil fuel","Renewable crop","Metal","Rock only"],answer:0},
  {question:"Coal is a:",options:["Fossil fuel","Vegetable","Metal","Liquid mineral"],answer:0},
  {question:"Hydroelectric power is generated mainly from:",options:["Moving water","Coal","Petroleum","Wind only"],answer:0},
  {question:"Solar energy comes from:",options:["The Sun","The Moon","Rivers","Coal"],answer:0},
  {question:"Deforestation means:",options:["Removal of forests","Planting forests","Formation of rivers","Growth of grass"],answer:0},
  {question:"Desertification is the process by which:",options:["Land becomes increasingly desert-like","Forests expand","Rivers deepen","Cities disappear"],answer:0},
  {question:"Conservation means:",options:["Wise management and protection of resources","Rapid destruction of resources","Mining only","Urbanization"],answer:0},
  {question:"A natural resource is:",options:["A resource obtained from nature","A manufactured machine","A building","A computer program"],answer:0},
  {question:"Renewable resources can:",options:["Be naturally replenished","Never be replaced","Only be mined","Only exist underground"],answer:0},
  {question:"An example of a renewable resource is:",options:["Solar energy","Coal","Petroleum","Natural gas"],answer:0},
  {question:"An example of a non-renewable resource is:",options:["Petroleum","Sunlight","Wind","Water"],answer:0},
  {question:"Transportation involves the movement of:",options:["People and goods","Only clouds","Only rainfall","Only minerals"],answer:0}
];

q["Christian Religious Studies"] = [
  {question:"According to Genesis, God created the world in:",options:["Six days","Three days","Ten days","Forty days"],answer:0},
  {question:"The first man created by God was:",options:["Adam","Abraham","Moses","Noah"],answer:0},
  {question:"The first woman was:",options:["Eve","Sarah","Mary","Rebecca"],answer:0},
  {question:"Adam and Eve lived in the:",options:["Garden of Eden","Garden of Gethsemane","Land of Egypt","City of Jericho"],answer:0},
  {question:"The serpent tempted:",options:["Eve","Sarah","Mary","Ruth"],answer:0},
  {question:"Cain killed his brother:",options:["Abel","Seth","Noah","Jacob"],answer:0},
  {question:"Noah built an:",options:["Ark","Altar","Temple","Palace"],answer:0},
  {question:"The flood occurred during the time of:",options:["Noah","Moses","David","Solomon"],answer:0},
  {question:"God called Abraham to leave:",options:["His country and relatives","Egypt","Jerusalem","Rome"],answer:0},
  {question:"Abraham's son of promise was:",options:["Isaac","Ishmael","Esau","Joseph"],answer:0},
  {question:"Isaac's son who later became Israel was:",options:["Jacob","Esau","Joseph","Benjamin"],answer:0},
  {question:"Jacob had how many sons who became the tribes of Israel?",options:["Twelve","Ten","Seven","Four"],answer:0},
  {question:"Joseph was sold by his brothers into:",options:["Egypt","Canaan","Rome","Babylon"],answer:0},
  {question:"Moses was raised in the household of:",options:["Pharaoh's daughter","Abraham","David","Solomon"],answer:0},
  {question:"God spoke to Moses through the:",options:["Burning bush","Temple","Ark","River"],answer:0},
  {question:"Moses led the Israelites out of:",options:["Egypt","Rome","Babylon","Persia"],answer:0},
  {question:"The Israelites crossed the:",options:["Red Sea","Dead Sea","Mediterranean Sea","Atlantic Ocean"],answer:0},
  {question:"The Ten Commandments were given to:",options:["Moses","David","Solomon","Joshua"],answer:0},
  {question:"The Israelites wandered in the wilderness for:",options:["Forty years","Ten years","Seven years","Seventy years"],answer:0},
  {question:"Joshua succeeded:",options:["Moses","David","Saul","Samuel"],answer:0},
  {question:"The first king of Israel was:",options:["Saul","David","Solomon","Samuel"],answer:0},
  {question:"David defeated:",options:["Goliath","Pharaoh","Saul","Absalom"],answer:0},
  {question:"David became king after:",options:["Saul","Solomon","Samuel","Moses"],answer:0},
  {question:"David's son who became king was:",options:["Solomon","Absalom","Jonathan","Samuel"],answer:0},
  {question:"Solomon was famous for his:",options:["Wisdom","Military weakness","Farming","Fishing"],answer:0},
  {question:"Solomon built the first:",options:["Temple in Jerusalem","Ark","Synagogue","Church"],answer:0},
  {question:"Jesus was born in:",options:["Bethlehem","Jerusalem","Nazareth","Capernaum"],answer:0},
  {question:"Jesus' mother was:",options:["Mary","Martha","Elizabeth","Ruth"],answer:0},
  {question:"Jesus was baptized by:",options:["John the Baptist","Peter","Paul","James"],answer:0},
  {question:"Jesus was baptized in the:",options:["Jordan River","Nile River","Red Sea","Sea of Galilee"],answer:0},
  {question:"Jesus chose how many apostles?",options:["Twelve","Seven","Ten","Forty"],answer:0},
  {question:"Peter was originally a:",options:["Fisherman","Tax collector","Soldier","Priest"],answer:0},
  {question:"Jesus' first miracle was performed at:",options:["Cana","Jerusalem","Bethlehem","Jericho"],answer:0},
  {question:"Jesus turned water into:",options:["Wine","Oil","Milk","Blood"],answer:0},
  {question:"Jesus taught his disciples the:",options:["Lord's Prayer","Ten Commandments","Psalms","Book of Proverbs"],answer:0},
  {question:"The parable of the Good Samaritan teaches:",options:["Love for one's neighbour","The importance of wealth","Military power","Political leadership"],answer:0},
  {question:"The prodigal son was welcomed back by his:",options:["Father","Brother","Teacher","King"],answer:0},
  {question:"Jesus raised Lazarus from:",options:["The dead","Prison","Exile","Slavery"],answer:0},
  {question:"Jesus was betrayed by:",options:["Judas Iscariot","Peter","John","Thomas"],answer:0},
  {question:"Judas betrayed Jesus for:",options:["Thirty pieces of silver","Ten pieces of gold","A crown","A house"],answer:0},
  {question:"Jesus was crucified at:",options:["Golgotha","Bethlehem","Nazareth","Cana"],answer:0},
  {question:"Jesus rose from the dead on the:",options:["Third day","Second day","Seventh day","Fortieth day"],answer:0},
  {question:"The resurrection is central to:",options:["Christian faith","Roman law","Greek mythology","Judaism only"],answer:0},
  {question:"After his resurrection Jesus ascended into:",options:["Heaven","Egypt","Rome","Galilee"],answer:0},
  {question:"The Holy Spirit descended on the disciples at:",options:["Pentecost","Passover","Christmas","Easter"],answer:0},
  {question:"The early church received the Holy Spirit in:",options:["Jerusalem","Rome","Egypt","Babylon"],answer:0},
  {question:"Paul was originally known as:",options:["Saul","Simon","Stephen","Silas"],answer:0},
  {question:"Paul was converted on the road to:",options:["Damascus","Jerusalem","Rome","Cana"],answer:0},
  {question:"Stephen was the first Christian:",options:["Martyr","King","Prophet","Apostle"],answer:0},
  {question:"Christianity teaches believers to:",options:["Love their enemies","Seek revenge","Reject forgiveness","Avoid all people"],answer:0},
  {question:"The greatest Christian commandment includes loving:",options:["God and one's neighbour","Only oneself","Only rulers","Only friends"],answer:0},
  {question:"Faith means:",options:["Trust and belief in God","Fear of government","Wealth","Political power"],answer:0},
  {question:"Repentance means:",options:["Turning away from sin","Increasing wealth","Seeking revenge","Ignoring wrongdoing"],answer:0},
  {question:"Forgiveness means:",options:["Pardoning an offender","Seeking revenge","Ignoring justice","Avoiding everyone"],answer:0},
  {question:"The fruit of the Spirit includes:",options:["Love","Hatred","Greed","Violence"],answer:0},
  {question:"The Bible is divided into:",options:["Old and New Testaments","Three Testaments","Four Testaments","Seven Testaments"],answer:0},
  {question:"The first book of the Bible is:",options:["Genesis","Exodus","Matthew","Psalms"],answer:0},
  {question:"The last book of the Bible is:",options:["Revelation","Genesis","Acts","Romans"],answer:0},
  {question:"The four Gospels are Matthew, Mark, Luke and:",options:["John","Paul","Peter","James"],answer:0},
  {question:"The Acts of the Apostles mainly describes:",options:["The early Christian church","The creation of the world","The life of Moses","The kings of Israel"],answer:0},
  {question:"Christian baptism symbolizes:",options:["New life in Christ","Political power","Economic success","Military victory"],answer:0}
];

fs.writeFileSync(
  './questions.js',
  'const questionBank = ' + JSON.stringify(q, null, 2) +
  ';\n\nmodule.exports = questionBank;\n'
);

console.log("Geography:", q["Geography"].length);
console.log("CRS:", q["Christian Religious Studies"].length);
