import json

p = "data/waec.json"

with open(p, encoding="utf-8") as f:
    data = json.load(f)

qs = [
("Agriculture is best defined as the science and art of","cultivating crops and rearing animals","selling farm tools","building houses","manufacturing machines"),
("The main aim of crop production is to","produce food and raw materials","destroy vegetation","reduce soil fertility","prevent harvesting"),
("A farmer who grows crops mainly for sale practices","commercial farming","subsistence farming","nomadic farming","shifting cultivation"),
("Subsistence farming is mainly practiced to","provide food for the farmer's family","produce crops only for export","supply factories only","make farm machinery"),
("A farm managed mainly for profit is a","commercial farm","subsistence farm","school farm","family garden"),
("The uppermost layer of the earth where plants grow is called","soil","rock","clay","gravel"),
("The process by which rocks break down to form soil is","weathering","erosion","leaching","irrigation"),
("The removal of topsoil by wind or water is","soil erosion","weathering","germination","pollination"),
("One major cause of soil erosion is","deforestation","mulching","terracing","cover cropping"),
("Planting trees to prevent erosion is called","afforestation","deforestation","irrigation","harvesting"),
("The soil particle with the largest size is","sand","clay","silt","humus"),
("The smallest soil particle is","clay","sand","gravel","silt"),
("A soil with a mixture of sand, silt and clay is","loam","gravel","peat","laterite"),
("The most suitable soil for many agricultural crops is","loamy soil","pure clay","pure sand","gravel"),
("Humus is formed mainly from","decomposed organic matter","rocks","sand particles","fertilizers"),
("A major benefit of humus is that it","improves soil fertility","destroys soil organisms","increases erosion","removes nutrients"),
("Soil pH measures","soil acidity or alkalinity","soil temperature","soil depth","soil colour"),
("A soil with pH below 7 is","acidic","alkaline","neutral","salty"),
("Lime is commonly used to","reduce soil acidity","increase soil erosion","destroy humus","remove nitrogen"),
("Organic manure includes","farmyard manure","urea only","NPK fertilizer","ammonium sulphate"),
("Green manure is","fresh plant material incorporated into soil","animal bones","chemical fertilizer","dry sand"),
("Compost is produced from","decomposed organic materials","rocks only","plastic materials","metal waste"),
("Nitrogen is important mainly for","vegetative growth","root cutting","fruit colour only","soil erosion"),
("Phosphorus promotes","root development","leaf burning","soil erosion","weed growth"),
("Potassium helps plants with","disease resistance and general growth","soil erosion","seed destruction","weed production"),
("NPK fertilizer supplies","nitrogen, phosphorus and potassium","nitrogen, potassium and calcium","nitrogen, phosphorus and chlorine","sodium, potassium and nitrogen"),
("A crop planted mainly to improve soil fertility is a","legume","cereal","tuber","root crop"),
("Leguminous plants can improve soil nitrogen through","nitrogen fixation","erosion","leaching","transpiration"),
("Rhizobium bacteria are commonly found in the roots of","legumes","maize","rice","yam"),
("Crop rotation involves","growing different crops on a field in sequence","growing one crop forever","burning crops annually","harvesting before planting"),
("One advantage of crop rotation is","control of pests and maintenance of soil fertility","increased erosion","loss of nutrients","destruction of humus"),
("Mixed cropping involves","growing two or more crops together","growing only one crop","raising animals only","planting trees only"),
("Intercropping means","growing different crops simultaneously on the same land","harvesting all crops at once","keeping animals in cages","burning crop residues"),
("Monocropping means","growing one crop on a piece of land","growing many crops together","raising livestock only","planting trees and fish"),
("Planting seeds directly in the field is","direct sowing","transplanting","grafting","budding"),
("Transplanting involves","moving seedlings from a nursery to the field","removing mature crops","cutting roots","drying seeds"),
("A nursery is used for","raising young seedlings","storing harvested grains","keeping tractors","processing meat"),
("A good seed should be","viable","damaged","diseased","immature"),
("Seed viability refers to its ability to","germinate","decay","change colour","produce fertilizer"),
("Germination is the process by which","a seed begins to grow","a plant dies","a crop is harvested","soil is ploughed"),
("One condition necessary for germination is","water","fertilizer only","sunlight only","wind"),
("A seed drill is used for","planting seeds","harvesting maize","spraying animals","milking cows"),
("A cutlass is commonly used for","clearing vegetation","milking cows","irrigating crops","measuring rainfall"),
("A hoe is commonly used for","weeding and making ridges","milking cattle","spraying chemicals","harvesting fish"),
("A sickle is mainly used for","harvesting grasses and cereals","ploughing soil","watering crops","planting trees"),
("A tractor is used mainly to","perform farm operations efficiently","produce seeds","pollinate crops","store fertilizer"),
("Ploughing involves","turning and loosening the soil","harvesting crops","watering animals","storing seeds"),
("Harrowing is done mainly to","break soil clods and prepare a fine seedbed","harvest fruits","control livestock","apply vaccines"),
("Ridging involves","forming raised ridges on the soil","removing all soil","planting trees in water","drying crops"),
("Weeds are plants that","grow where they are not wanted","are always useful crops","produce fertilizer","are farm animals"),
("One harmful effect of weeds is","competition with crops for nutrients","improvement of crop yield","increase in soil fertility","prevention of erosion"),
("Herbicides are chemicals used to control","weeds","insects","rodents","birds"),
("Insecticides are used to control","insects","weeds","fungi","bacteria only"),
("Fungicides are used to control","fungal diseases","weeds","rodents","birds"),
("Pesticides are substances used to","control pests","increase rainfall","improve soil texture","harvest crops"),
("An example of a biological pest control method is","using natural predators","burning all crops","removing soil","overwatering plants"),
("Crop pests can cause","reduction in crop yield","increase in harvest always","improved germination","increased soil depth"),
("A disease caused by fungi is commonly controlled with","fungicides","herbicides","rodenticides","fertilizers"),
("Pollination is the transfer of pollen from","anther to stigma","stigma to root","root to leaf","ovary to anther"),
("Fertilization in flowering plants involves","fusion of male and female gametes","movement of water","formation of leaves","growth of roots"),
("The male reproductive part of a flower is the","stamen","pistil","ovary","sepal"),
("The female reproductive part of a flower is the","pistil","stamen","anther","filament"),
("The part of a flower that receives pollen is the","stigma","anther","filament","sepal"),
("The fruit develops mainly from the","ovary","anther","stigma","sepal"),
("A seed develops from the","ovule","stigma","anther","petal"),
("Maize belongs to the group of","cereals","legumes","tubers","vegetables"),
("Groundnut is a","legume","cereal","tuber","fruit"),
("Cassava is mainly grown for its","tuberous roots","leaves only","flowers","seeds"),
("Yam is a","tuber crop","cereal","legume","oil crop"),
("Oil palm is important mainly for","palm oil production","grain production","latex production","fibre production"),
("Cocoa is mainly grown for","beans used in chocolate production","roots","tubers","leaves"),
("Rubber is obtained from","latex","seeds","roots","flowers"),
("Cotton is mainly grown for its","fibre","roots","tubers","oil only"),
("Rice is mainly classified as a","cereal crop","legume","tuber","root crop"),
("A livestock animal kept mainly for milk is","cattle","broiler","ram","rabbit"),
("A young female cattle is called a","heifer","bull","calf","ram"),
("An adult male cattle is called a","bull","cow","heifer","ewe"),
("An adult female sheep is called a","ewe","ram","doe","buck"),
("An adult male sheep is called a","ram","ewe","sow","boar"),
("An adult female goat is called a","doe","buck","ewe","ram"),
("An adult male goat is called a","buck","doe","sow","bull"),
("A young chicken is called a","chick","calf","kid","lamb"),
("A male chicken is called a","cock","hen","drake","gander"),
("A female chicken is called a","hen","cock","ram","boar"),
("Broilers are chickens reared mainly for","meat","eggs","feathers","breeding only"),
("Layers are chickens reared mainly for","egg production","meat production","milk","wool"),
("A castrated male cattle is called an","ox","bull","calf","ram"),
("The process of giving birth in cattle is called","calving","kidding","lambing","farrowing"),
("The process of giving birth in pigs is called","farrowing","calving","kidding","lambing"),
("The process of giving birth in goats is called","kidding","calving","farrowing","lambing"),
("The process of giving birth in sheep is called","lambing","kidding","farrowing","calving"),
("A balanced livestock ration contains","all necessary nutrients in suitable proportions","water only","protein only","minerals only"),
("Protein is needed by livestock mainly for","growth and tissue repair","body cooling only","digestion only","water storage"),
("Carbohydrates mainly provide","energy","vitamins","minerals","antibodies"),
("Minerals are important for","bones and body functions","colouring feathers only","soil erosion","weed control"),
("Vaccination is used mainly to","prevent diseases","increase animal size instantly","provide water","improve soil fertility"),
("A veterinary doctor specializes in","animal health","crop marketing","soil testing","farm accounting"),
("Quarantine means","isolating animals to prevent disease spread","feeding animals","selling livestock","vaccinating crops"),
("Artificial insemination involves","introducing semen into a female animal artificially","feeding young animals","removing horns","castrating males"),
("Farm records are important because they","help the farmer make informed decisions","increase rainfall","prevent all diseases","replace farm tools"),
("A farm inventory is a record of","farm assets and items","rainfall only","animal diseases only","crop colours"),
("Farm budgeting helps to","plan expected income and expenditure","control rainfall","produce seeds","prevent germination"),
("Agricultural extension services provide farmers with","technical information and advice","bank loans only","farm machinery only","animal feed only"),
("Marketing involves","buying and selling agricultural products","planting seeds only","watering crops","vaccinating animals"),
("Storage is important because it","reduces post-harvest losses","increases pests","causes spoilage","reduces food quality"),
("A silo is mainly used for storing","grains","milk","eggs","meat"),
("A barn may be used for storing","farm produce and housing livestock","fish only","fertilizer only","rainwater"),
("Irrigation is the artificial application of","water to crops","fertilizer to animals","pesticide to soil only","seeds to crops"),
("Drainage involves","removing excess water from soil","adding water to crops","planting seeds","harvesting grains"),
("Terracing is useful mainly on","sloping land","flat land only","swamps only","deserts only"),
("Mulching helps to","conserve soil moisture","increase erosion","destroy crops","remove nutrients"),
("A cover crop helps to","protect the soil from erosion","increase weed growth","destroy humus","reduce soil cover"),
("Agroforestry involves","combining trees with crops or livestock","growing only cereals","keeping only poultry","farming without soil"),
("Fish farming is known as","aquaculture","apiculture","sericulture","horticulture"),
("Bee farming is known as","apiculture","aquaculture","sericulture","floriculture"),
("The rearing of silkworms is called","sericulture","apiculture","aquaculture","horticulture"),
("Horticulture deals mainly with","fruits, vegetables and ornamental plants","livestock only","fish only","forestry only"),
("Forestry is concerned with","management of forests and forest resources","raising poultry","fish production","crop harvesting"),
("A major advantage of mechanization is","increased efficiency and reduced labour requirement","reduced productivity","increased manual labour","lower farm output"),
("One disadvantage of excessive mechanization is","soil compaction","increased hand labour","reduced farm size","improved soil structure always"),
("The removal of unwanted branches from a tree is","pruning","mulching","grafting","threshing"),
("Grafting is a method of","vegetative propagation","soil erosion","harvesting","irrigation"),
("Asexual reproduction in plants produces offspring that are usually","genetically similar to the parent","always unrelated","larger than the parent","without roots"),
("The process of separating grains from harvested crops is","threshing","ploughing","germination","pollination"),
("Winnowing separates grain from","chaff","roots","soil","water"),
("Harvesting means","removing mature crops from the field","planting seeds","watering crops","fertilizing soil"),
("Post-harvest losses occur","after crops are harvested","before planting","during germination only","during pollination"),
("One way to reduce post-harvest losses is","proper storage","poor handling","delayed harvesting","excessive moisture"),
("Agricultural cooperatives help farmers by","pooling resources and improving marketing","preventing farming","destroying crops","reducing access to markets"),
]

assert len(qs) >= 100
qs = qs[:100]

questions = []
for i, item in enumerate(qs):
    question, correct, b, c, d = item
    options = [correct, b, c, d]
    shift = i % 4
    options = options[shift:] + options[:shift]
    questions.append({
        "question": question,
        "options": options,
        "answer": options.index(correct)
    })

data["Agricultural Science"] = questions

with open(p, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("Agricultural Science saved:", len(questions))
